### ISSUE TITLE
TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid

### ISSUE THREAD

**Issue by pascalhabluetzel** [DominikBuchner/BOLDigger-commandline#5]
calling
```
$ boldigger-cline ie_coi <username> <password> ./test03_20220407/results-2022-04-07-16\:26/barcode03_nonchimeras.fasta output
```
results in
```
Login successfull
00:11:05: Requesting BOLD. This will take a while.                              
Downloading results: 100%|██████████████████████| 10/10 [00:50<00:00,  5.04s/it]
00:14:31: Parsing html.                                                         
Requesting BOLD:   0%|                                   | 0/19 [03:25<?, ?it/s]
Traceback (most recent call last):
  File "/PATH/bin/boldigger-cline", line 8, in <module>
    sys.exit(main())
  File "/PATH/lib/python3.8/site-packages/boldigger_cline/__main__.py", line 42, in main
    boldblast_coi.main(args.username, args.password, args.fasta_path, args.output_folder, args.batch_size)
  File "/PATH/lib/python3.8/site-packages/boldigger_cline/boldblast_coi.py", line 67, in main
    dataframes = save_as_df(html_list, sequences_names[querys.index(query)])
  File "/PATH/lib/python3.8/site-packages/boldigger/boldblast_coi.py", line 106, in save_as_df
    result = pd.concat(tables, axis = 0)
  File "/PATH/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/PATH/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 347, in concat
    op = _Concatenator(
  File "/PATH/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 437, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid
```

It seems that the script wants to concatenate objects of type 'str'. Unfortunately I could not find out what exactly caused this issue. Can someone help?

**Comment by DominikBuchner** [comment]
Will work on this asap. Did not maintain boldigger-cline for a while.
