### ISSUE TITLE
API verification fails

### ISSUE THREAD

**Issue by naurasd** [DominikBuchner/BOLDigger-commandline#8]
Hi (me again, I know),

API verification fails. See error message:

$ boldigger-cline api_verification trial.xlsx COI_cluster_reps_curated_no_contam.fa
14:55:20: Starting API verification.
14:55:20: Collection OTUs without species level identification and high similarity.
Traceback (most recent call last):
  File "c:\users\nauras\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nauras\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nauras\Programs\Python\Python39\Scripts\boldigger-cline.exe\__main__.py", line 7, in <module>
  File "c:\users\nauras\programs\python\python39\lib\site-packages\boldigger_cline\__main__.py", line 73, in main
    api_verification.main(args.xlsx_path, args.fasta_path)
  File "c:\users\nauras\programs\python\python39\lib\site-packages\boldigger_cline\api_verification.py", line 17, in main
    raw_data, data_to_check, seq_dict = extract_data(xlsx_path, fasta_path)
  File "c:\users\nauras\programs\python\python39\lib\site-packages\boldigger\api_verification.py", line 31, in extract_data
    raw_data = pd.read_excel(xlsx_path, sheet_name = 'BOLDigger hit')
  File "c:\users\nauras\programs\python\python39\lib\site-packages\pandas\util\_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "c:\users\nauras\programs\python\python39\lib\site-packages\pandas\io\excel\_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "c:\users\nauras\programs\python\python39\lib\site-packages\pandas\io\excel\_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "c:\users\nauras\programs\python\python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 22, in __init__
    super().__init__(filepath_or_buffer)
  File "c:\users\nauras\programs\python\python39\lib\site-packages\pandas\io\excel\_base.py", line 353, in __init__
    self.book = self.load_workbook(filepath_or_buffer)
  File "c:\users\nauras\programs\python\python39\lib\site-packages\pandas\io\excel\_xlrd.py", line 37, in load_workbook
    return open_workbook(filepath_or_buffer)
  File "c:\users\nauras\programs\python\python39\lib\site-packages\xlrd\__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported

Seems like a problem with reading Excel files?? BOLDiger results file with BOLDigger top hits attached.
[trial.xlsx](https://github.com/DominikBuchner/BOLDigger-commandline/files/9542445/trial.xlsx)

I have upgraded to the most recent version of boldigger-cline, but for some reason it keeps saying version 1.0.0 is installed.

Cheers

Nauras

**Comment by DominikBuchner** [comment]
Will be fixed by using the correct upgrade. See my comment on the other issue.

**Comment by naurasd** [comment]
Thanks, appreciate it.
